apiVersion: v1
kind: Namespace
metadata:
  name: ejemplo1
---
apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  namespace: ejemplo1
spec:
  containers:
    - name: hello-container
      image: nginx
      ports:
        - containerPort: 80